GET  http://localhost:8050/events
Content-Type: application/json

###

GET  http://localhost:8050/announcements
Content-Type: application/json

###

GET  http://localhost:8050/sermons
Content-Type: application/json

###

GET  http://localhost:8050/slideshow
Content-Type: application/json

###

GET  http://localhost:8050/leaders
Content-Type: application/json
